version: 2

updates:
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: ex_doc
        versions:
          - ">= 0.32.0"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
